# Generated by Django 5.0.2 on 2024-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default=None, upload_to='medicine/%y/%m'),
        ),
    ]
