# Generated by Django 5.0.4 on 2024-04-10 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_remove_cart_name_remove_cart_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
