# Generated by Django 5.0.4 on 2024-04-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_payment_id_payment_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailcart',
            old_name='id_payment',
            new_name='payment',
        ),
    ]
