# Generated by Django 5.0.4 on 2024-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerproduct',
            options={'verbose_name': 'Offer Product', 'verbose_name_plural': 'Offer Products'},
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
