# Generated by Django 5.0.4 on 2024-04-19 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_remove_detailinvoice_id_invoice_and_more'),
    ]

    operations = [

    ]
