# Generated by Django 5.0.4 on 2024-04-19 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_remove_order_status_order_status_id_delete_drugtype'),
    ]

    operations = [

        migrations.AddField(
            model_name='medicine',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.subcategory'),
        )

    ]
