# Generated by Django 5.0.4 on 2024-04-19 19:01

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_remove_order_status_medicine_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={'category': django.db.models.expressions.OuterRef('category')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.subcategory'),
        ),
    ]
