# Generated by Django 5.0.4 on 2024-04-19 19:25

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_remove_order_status_order_status_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='medicine',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={'category_id': django.db.models.expressions.OuterRef('category_id')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.subcategory'),
        ),
    ]
