# Generated by Django 5.0.4 on 2024-04-19 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_remove_order_status_order_status_id_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.category'),
        ),

    ]
