# Generated by Django 5.0.4 on 2024-04-22 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_remove_order_status_category_parent_order_status_id'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='medicine',
            name='content',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='source',
        ),
        migrations.AddField(
            model_name='medicine',
            name='producer',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='where_production',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='trademark',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status_id',
            field=models.CharField(
                choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'),
                         ('Delivered', 'Delivered')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),

    ]
